version: '3'
volumes: 
  bundle: 
services: 
  app:
    build: .
    ports: 
      - 3000:3000
      - 8080:8080
    volumes: 
      - bundle:/usr/local/bundle
      - .:/usr/src/app:delegated
      - /usr/src/app/frontend/node_modules
    stdin_open: true
    tty: true
    command: /bin/sh -c "bundle install; rm /usr/src/app/tmp/pids/server.pid; rails s -b 0.0.0.0 -p 3000"